name: Shellcheck
on: [push]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Set up shellcheck
      run: |
        apt update
        apt install -y shellcheck        
    - name: Analysing the code with shellcheck
      run: shellcheck -S warning *.sh
